##############################################################################
#                            Development Profile                             #
##############################################################################

# -Dapp.datasource.channel.path={path}

spring:
  config:
    activate:
      on-profile: dev

# data sources
datasource:
  purchase:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:${app.datasource.channel.path}
    username: sa
    password:

    poolName: purchaseDbPool
    maximumPoolSize: 50
    minimumIdle: 20
    maxLifetime: 180000
    connectionTimeout: 30000
    idleTimeout: 30000
    connectionTestQuery: SELECT 1
    pool-prepared-statements: true
    max-open-prepared-statements: 250
